### ISSUE TITLE
Trace error when processing many files

### ISSUE THREAD

**Issue by jpdelima** [MichalCz/scramjet#8]
Hi,

Using scramjet to extract translations strings from my HTML files I get warnings like this:

(node:33092) Warning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit

Scramjet works OK though. Good to fix anyway.

Thx

**Comment by MichalCz** [comment]
Yeah. That may be annoying - this is caused by piping a lot of files into a single transform stream. I should be increasing the limit in this case or actually merge the streams into immediate ones (which won't add much complexity).

You can expect a fix on Monday...

**Comment by MichalCz** [comment]
Hey @jpdelima,

Thanks for the test. Fix confirmed in v1.5.0
